### ISSUE TITLE
Compilation error on ubuntu 22.04

### ISSUE THREAD

**Issue by Virgileboat** [2b-t/myactuator_rmd#15]
Hello, I have the following error when I try to compile  the project:
```
 /myactuator_rmd/include/myactuator_rmd/protocol/single_motor_message.hpp:54:25: error: variable of non-literal type 'std::stringstream' (aka 'basic_stringstream<char>') cannot be defined in a constexpr constructor
      std::stringstream ss {};

```
Do you have any idea of how to fix it?

**Comment by 2b-t** [comment]
_Hi @Virgileboat_ 
Interesting that this did not come up for anyone else before but this seems to be a mistake of mine. A `constexpr` constructor should not contain `std::stringstream`. I will have to make a few minor changes for this. Which compiler are you using (e.g. `$ gcc -v` in case you are using GCC)?
Can you in the meanwhile uncomment the following lines and compile it again? https://github.com/2b-t/myactuator_rmd/blob/1d1595ce9a0ea7b9b839f89b137176f54bc9668c/include/myactuator_rmd/protocol/single_motor_message.hpp#L53-L57

**Comment by Virgileboat** [comment]
Hi 2b-t
I checked the compiler and changed it to g++, and now it works fine.
Thanks for your help !

**Comment by 2b-t** [comment]
Excellent @Virgileboat ! Were you using Clang previously or which compiler were you using? I would like to fix this and make sure that nobody runs into the same issue.
_Thanks!_

**Comment by Virgileboat** [comment]
It seems that the error was caused by a broken compiler that was used by default. 

By the way, Did you test the library with the new range of actuators ( x12-150, x8-90, etc.)? These motors don't seem to work with the current communication protocol used.  (Let me know if you'd like me to open a separate issue for this. )

**Comment by 2b-t** [comment]
This driver currently is based on protocol [V3.8](https://github.com/2b-t/myactuator_rmd/blob/main/include/myactuator_rmd/version.hpp). Many of their newer actuators are using [V3.9](https://www.myactuator.com/downloads-x-series) which has only minor changes with respect to V3.8. The protocol for X4-24, X8-90, X12-150 and X15-400 on the other hand is quite different. Unfortunately I do not have a corresponding actuator to test it and it is therefore unlikely that I will implement it.
I heard though that the manufacturer plans to move all of their actuators to the V3.9 protocol. So potentially there will be a firmware update for it at a later point.
