### ISSUE TITLE
1320 dps enforcement - max speed check

### ISSUE THREAD

**Issue by dani-carbonell** [2b-t/myactuator_rmd#3]
Hi Tobit,

I am testing this SDK with a [RMD-X6-S](https://ozrobotics.com/shop/rmd-x6-s-v3-micro-servo-motor-with-v3-drive-delicate-and-lightweight-in-350g-can-bus/)
This motor can in theory achive speeds of 6000RPM (36000dps)
I think it is not related but it comes with a newer version of the protocol [V4.01](https://www.myactuator.com/_files/ugd/cab28a_4396d7519700437c979530e3acdb4bd7.pdf)

I am trying to achive high speeds with it.
Is there a reason for the speed check in the [code](https://github.com/2b-t/myactuator_rmd/blob/ac05c777302859ecae35e3b66ea97facc330e598/src/protocol/requests.cpp#L81)
[](url)?

![RDM-X6-P6](https://github.com/2b-t/myactuator_rmd/assets/7487001/1c1fc07c-a935-40c8-a848-e0022fe2935c)

**Comment by 2b-t** [comment]
_Hi Dani,_
There is not, just adjust the check to a value that is reasonable for your actuator for now. I will have to rethink some of these limits and make them use [values in the actuator constants](https://github.com/2b-t/myactuator_rmd/blob/main/include/myactuator_rmd/actuator_constants.hpp). Just leave this issue open and I will close it in one of the following weeks.
I have also updated the code quite significantly over the last two weeks so you might want to pull the latest version as well...
